-- 1. What is the total number of orders?
SELECT DISTINCT COUNT(order_id) FROM orders
-- Insight: 830 orders are present.

-- 2. What is the total revenue generated?
SELECT SUM(order_details.unit_price * order_details.quantity * (1-order_details.discount)) AS total_revenue FROM order_details
-- Insight: 1265793.038653364 is the total revenue generated.

-- 3. Show total revenue by product (with product name), sorted highest to lowest.
SELECT product_name,SUM(order_details.unit_price * order_details.quantity * (1-order_details.discount))
AS revenue_total FROM products INNER JOIN order_details
ON products.product_id = order_details.product_id
GROUP BY products.product_name
ORDER BY revenue_total DESC
-- Insight: The best selling product is Côte de Blaye with a revenue of 141396.7356273254.

-- 4. Show total revenue generated by each customer (with customer name), sorted highest to lowest.
SELECT customers.contact_name,SUM(order_details.unit_price * order_details.quantity * (1-order_details.discount))
AS total_revenue
FROM customers INNER JOIN orders
ON customers.customer_id = orders.customer_id INNER JOIN order_details
ON orders.order_id = order_details.order_id
GROUP BY customers.contact_name
ORDER BY total_revenue DESC
-- Insight: Most revenue generated customer is Horst Kloss with 110277.30503039382.

-- 5. Show total number of orders placed by each customer, with customer name, sorted from highest to lowest.
SELECT COUNT(orders.order_id) AS total_orders,customers.contact_name FROM orders INNER JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.contact_name
ORDER BY total_orders DESC
-- Insight: The highest orders are from Jose Pavarotti

-- 6. Show the total revenue for each product category, with category name, sorted highest to lowest.
SELECT categories.category_name,products.category_id, SUM(order_details.unit_price * order_details.quantity * (1-discount))
AS total_revenue
FROM categories INNER JOIN products
ON categories.category_id = products.category_id INNER JOIN order_details
ON products.product_id = order_details.product_id
GROUP BY categories.category_name,products.category_id
ORDER BY total_revenue DESC
-- Insight: Product category had the most generated revenue was beverages.

-- 7. Show total revenue for each month, sorted by year and month.
SELECT TO_CHAR(orders.order_date,'YYYY-MM') AS order_month, SUM(order_details.unit_price * order_details.quantity * (1-order_details.discount)) 
AS total_revenue
FROM orders INNER JOIN order_details ON orders.order_id = order_details.order_id
GROUP BY TO_CHAR(orders.order_date,'YYYY-MM')
ORDER BY order_month
-- Insight: This code helps to find the sales trend over time.

-- 8. Show the top 5 customers in the USA by total revenue, with company name.
SELECT SUM(order_details.unit_price * order_details.quantity * (1-order_details.discount)) AS revenue,
customers.company_name
FROM order_details INNER JOIN orders ON order_details.order_id = orders.order_id INNER JOIN customers
ON orders.customer_id = customers.customer_id
WHERE customers.country LIKE 'USA'
GROUP BY customers.company_name
ORDER BY revenue DESC
LIMIT 5
-- Insight: Used to return the top 5 customers in USA. 

-- 9. Show countries with more than 5 customers.
SELECT country,COUNT (customer_id) FROM customers
GROUP BY country
HAVING COUNT(customer_id) > 5
-- Insight: Identifies countries with high customer presence.

-- 10. Show average unit price for each product category.
SELECT AVG(order_details.unit_price) AS avg_price, categories.category_name 
FROM categories INNER JOIN products ON categories.category_id = products.category_id 
INNER JOIN order_details ON products.product_id = order_details.product_id
GROUP BY categories.category_name
-- Insight: Used to compare the prices among categories.

-- 11. Classify customers based on total revenue
SELECT customers.contact_name, SUM(order_details.unit_price * order_details.quantity * (1-order_details.discount)) AS revenue,
CASE  
WHEN SUM(order_details.unit_price * order_details.quantity * (1-order_details.discount)) BETWEEN 1 AND 5000 THEN 'Cheapskates'
WHEN SUM(order_details.unit_price * order_details.quantity * (1-order_details.discount)) BETWEEN 5001 AND 10000 THEN 'Average Customers'
ELSE 'Top Customers'
END AS customer_priority
FROM order_details INNER JOIN orders ON order_details.order_id = orders.order_id INNER JOIN 
customers ON orders.customer_id = customers.customer_id
GROUP BY contact_name
ORDER BY customer_priority
-- Insight: Groups customers based on revenue.

-- 12. Which products have never been ordered?
SELECT product_name FROM products LEFT OUTER JOIN order_details
ON products.product_id = order_details.product_id
WHERE order_details.product_id IS NULL
-- Insight: All products have been ordered.

-- 13. Who are the top 3 customers by revenue in each country?
WITH customer_revenue AS (
SELECT SUM(order_details.unit_price * order_details.quantity * (1-order_details.discount)) AS revenue,
customers.country, customers.contact_name FROM order_details INNER JOIN orders
ON order_details.order_id = orders.order_id INNER JOIN customers 
ON orders.customer_id = customers.customer_id 
GROUP BY customers.country, customers.contact_name
),
ranked_customers AS (
SELECT country, contact_name, revenue, RANK() OVER(PARTITION BY country
ORDER BY revenue) AS customer_rank FROM customer_revenue
)
SELECT country, contact_name, revenue, customer_rank FROM ranked_customers
WHERE customer_rank <= 3
ORDER BY revenue,country DESC
-- Insight: To identify top 3 customers based on their country.

-- 14. Show the top 2 products by revenue in each category
WITH product_revenue AS (
SELECT products.product_name, categories.category_name, SUM(order_details.unit_price * order_details.quantity *(1-order_details.discount)) AS revenue
FROM order_details INNER JOIN products ON order_details.product_id = products.product_id
INNER JOIN categories ON products.category_id = categories.category_id
GROUP BY categories.category_name, products.product_name
), ranked_products AS (
SELECT product_name, category_name, revenue, RANK() OVER(PARTITION BY category_name ORDER BY revenue DESC)
AS product_rank FROM product_revenue
)
SELECT product_name, category_name, revenue, product_rank FROM ranked_products
WHERE product_rank <= 2
ORDER BY revenue DESC
-- Insight: To identify the top 2 performing products within each category.
